name: Create Submission from Main
on:
  push:
    branches: ['main']
permissions:
  contents: write
jobs:
  submit:
    uses: curvenote/actions/.github/workflows/submit.yml@v1
    with:
      venue: ophusgroup
      kind: article
      collection: articles
      id-pattern-regex: '^colab-[a-zA-Z0-9_-]{1,30}$'
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
